package net.dom53.inkita.domain.model.filter

enum class KavitaField(
    val id: Int,
) {
    Summary(0),
    SeriesName(1),
    PublicationStatus(2),
    Languages(3),
    AgeRating(4),
    UserRating(5),
    Tags(6),
    CollectionTags(7),
    Translators(8),
    Characters(9),
    Publisher(10),
    Editor(11),
    Artist(12),
    Letterer(13),
    Colorist(14),
    Inker(15),
    Penciller(16),
    Writers(17),
    Genres(18),
    Libraries(19),
    ReadingProgress(20),
    Formats(21),
    ReleaseYear(22),
    ReadTime(23),
    Path(24),
    FilePath(25),
    WantToRead(26),
    ReadDate(27),
    AverageRating(28),
    Imprint(29),
    Team(30),
    Location(31),
    LastRead(32),
    FileSize(33),
}
