name: 📝 Quick note
description: Fast self-report for ideas, bugs or reminders
labels: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe what you found or want to add.
      placeholder: |
        Example:
          "Reader sometimes jumps pages"
          "Add button for quick continue reading"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details (optional)
      placeholder: |
        Add any details if you want.

  - type: input
    id: type
    attributes:
      label: Type
      description: Bug, Feature, Idea... (optional)
      placeholder: |
        Example: "Bug"

  - type: checkboxes
    id: acks
    attributes:
      label: Acknowledgements
      options:
        - label: This is a quick personal note and may not include full details.
          required: true
